{% set name = "opencv-python-headless" %}
{% set version = "5.0.0.93" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: b82f9831daab90b725c7c1ee1b36cb5732c367096ac76d119e64e14eb70d5f3c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # No setuptools <70 for py313
  skip: true  # [py<36 or py>312]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - python
    - numpy {{ numpy }}
    - packaging
    - pip
    - scikit-build >=0.14.0
    - setuptools >=59.2.0  # [py<312]
    - setuptools <70.0.0  # [py>=312]
  run:
    - python
    - numpy ==2.0.2  # [py>=39 and py<313]

test:
  imports:
    - cv2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opencv/opencv-python
  summary: Wrapper package for OpenCV python bindings.
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE-3RD-PARTY.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - nilchia
